sudo: required

language: bash

services:
  - docker

before_install:
  # Update docker for multi-stage build
  - sudo service docker stop
  - curl -fsSL https://get.docker.com/ | sudo sh

  # Prepare qemu
  - docker run --rm --privileged multiarch/qemu-user-static:register --reset
  # Get qemu-arm-static binary
  - mkdir tmp
  - >
    pushd tmp &&
    curl -L -o qemu-arm-static.tar.gz https://github.com/multiarch/qemu-user-static/releases/download/v2.9.1-1/qemu-arm-static.tar.gz &&
    tar xzf qemu-arm-static.tar.gz &&
    curl -L -o qemu-aarch64-static.tar.gz https://github.com/multiarch/qemu-user-static/releases/download/v2.9.1-1/qemu-aarch64-static.tar.gz &&
    tar xzf qemu-aarch64-static.tar.gz &&
    popd

script:
  # Build all images
  - docker build --build-arg PLATFORM=linux-amd64 -t raymondmm/node-red-homekit:linux-amd64 -f Dockerfile.linux-amd64 .
  - docker build --build-arg PLATFORM=linux-arm -t raymondmm/node-red-homekit:linux-arm -f Dockerfile.linux-arm32v7 .

after_success:
  - > 
    if [ -n "$TRAVIS_TAG" ]; then
      # Docker login
      echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
      
      # Docker Tag
      docker tag raymondmm/node-red-homekit:linux-amd64 raymondmm/node-red-homekit:${TRAVIS_TAG}-linux-amd64
      docker tag raymondmm/node-red-homekit:linux-arm raymondmm/node-red-homekit:${TRAVIS_TAG}-linux-arm
      
      # Docker Push
      docker push raymondmm/node-red-homekit:${TRAVIS_TAG}-linux-amd64
      docker push raymondmm/node-red-homekit:${TRAVIS_TAG}-linux-arm
      
      # Download manifest-tool
      wget https://github.com/estesp/manifest-tool/releases/download/v0.7.0/manifest-tool-linux-amd64
      mv manifest-tool-linux-amd64 manifest-tool
      chmod +x manifest-tool
      
      # Create and push manifest-list
      ./manifest-tool push from-args --platforms linux/amd64,linux/arm --template "raymondmm/node-red-homekit:${TRAVIS_TAG}-OS-ARCH" --target "raymondmm/node-red-homekit:$TRAVIS_TAG"
      ./manifest-tool push from-args --platforms linux/amd64,linux/arm --template "raymondmm/node-red-homekit:${TRAVIS_TAG}-OS-ARCH" --target "raymondmm/node-red-homekit:latest"
    fi
